### ISSUE TITLE
Opaque Error on refresh: Debug Failure.

### ISSUE THREAD

**Issue by Veetaha** [senkenn/sqlsurge#46]
I installed the extension, installed `sqls` and configured it with a test DB that I have in my environment the following way:

```yml
lowercaseKeywords: false
connections:
  - alias: blue-stack
    driver: postgresql
    dataSourceName: postgresql://test:tester@localhost:5432/catalog
```

> [!NOTE]
> I don't understand how `sqlsurge` is supposed to know that I use a particular connection in my code, because that config specifies a list. Maybe it's part of the problem?

However, when I try to save a rust source file, trigger completions or manually run `sqlsurge: Format SQL` command I get the following pop-up every time.

![image](https://github.com/senkenn/sqlsurge/assets/36276403/83de4c3a-f5c1-484a-a44e-757eb5a26f72)

You can see the `sqls` logs in the output above. However, there is no output from `sqlsurge`:

![image](https://github.com/senkenn/sqlsurge/assets/36276403/0f8f1371-3eb4-4996-a529-34624d30e803)

Is there any way I can get more detailed logs from `sqlsurge` for you?

## Environment

It may be important to note, that I'm using VSCode Remote SSH. The extension is installed on a remote machine.

**Comment by senkenn** [comment]
@Veetaha Thank you for report and using this!
This issue was resolved at below issue and you can use fixed version with v0.5.1.
- #38

**Comment by Veetaha** [comment]
Hi, I still have this problem on 0.5.1. Is there any way I can get more detailed logs from `sqlsurge`? Could you also clarify how `sqlsurge` discovers the correct DB to use from `sqls` config when providing completions or does it provide completions for all configured DBs?

**Comment by Veetaha** [comment]
I can't paste the full Rust code because it's my work project. However, I also have a [personal project in a public repo](https://github.com/Veetaha/snowpity) that uses `sqlx`. To reproduce you can follow these steps:
```
# Clone the repository
git clone git@github.com:Veetaha/snowpity.git

# Start the DB
docker compose up --wait postgres

# [Optional]. Apply sqlx migrations
sqlx migrate run --source crates/snowpity-tg/migrations
```

Now open, for example [this file](https://github.com/Veetaha/snowpity/blob/8c0355d7e8dc639fcdb6b788a36b8fc1cc1477e3/crates/snowpity-tg/src/posting/derpibooru/db.rs#L18) and try saving it in VSCode. You should see the error pop up.

**Comment by Veetaha** [comment]
**UPD**: forgot to say that you should specify `DATABASE_URL` in `.env` and update the config for sqls:
```yml
lowercaseKeywords: false
connections:
  - alias: snowpity
    driver: postgresql
    dataSourceName: postgres://snowpity:my-secret-postgres-password@localhost:5432/snowpity
```

**Comment by senkenn** [comment]
@Veetaha I could fixed this issue. you can check at `v0.5.2`.

**Comment by Veetaha** [comment]
Yep, I don't see the error now. However, I get no completions

**Comment by senkenn** [comment]
Are you set this setting in settings.json?
```json
"editor.quickSuggestions": {
    "strings": true
}
```
VSCode's auto completion in strings is disabled by default.

**Comment by senkenn** [comment]
Sorry, apparently there's a bug that prevents completion except for the first syntax.
I try to fix it.

**Comment by senkenn** [comment]
I created an issue: https://github.com/senkenn/sqlsurge/issues/48
If you have any problems, please tell me about this issue.

**Comment by Veetaha** [comment]
> Are you set this setting in settings.json?

Yes, this config is set.
